version: "3.8"

services:
  app:
    container_name: dev_url_metadata_inventory_backend
    image: url_metadata_inventory_backend:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:7.0
    container_name: dev_metadata_inventory_mongodb
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
    driver: local

networks:
  metadata_network:
    driver: bridge
